management:
  security:
    enabled: false
    
security:
  basic:
    enabled: false
    
logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.integration: DEBUG
    org.springframework.amqp: DEBUG
    
spring:
  activemq:
    in-memory: true
    
jms:
  wmsInQueue:
    name: wmsInQueue  
  wmsOutQueue:
    name: wmsOutQueue